{"trial_id": "079", "hyperparameters": {"space": [{"class_name": "Choice", "config": {"name": "filters_block1", "default": 32, "conditions": [], "values": [32, 64], "ordered": true}}, {"class_name": "Choice", "config": {"name": "filters_block2", "default": 64, "conditions": [], "values": [64, 128], "ordered": true}}, {"class_name": "Int", "config": {"name": "dense_units", "default": null, "conditions": [], "min_value": 256, "max_value": 512, "step": 128, "sampling": "linear"}}, {"class_name": "Choice", "config": {"name": "learning_rate", "default": 0.01, "conditions": [], "values": [0.01, 0.001, 0.0001], "ordered": true}}, {"class_name": "Float", "config": {"name": "dropout_dense", "default": 0.3, "conditions": [], "min_value": 0.3, "max_value": 0.6, "step": 0.1, "sampling": "linear"}}, {"class_name": "Choice", "config": {"name": "optimizer", "default": "adam", "conditions": [], "values": ["adam", "rmsprop", "sgd", "adagrad"], "ordered": false}}], "values": {"filters_block1": 32, "filters_block2": 64, "dense_units": 512, "learning_rate": 0.01, "dropout_dense": 0.4, "optimizer": "adagrad"}}, "metrics": {"metrics": {}}, "score": null, "best_step": 0, "status": "FAILED", "message": "Traceback (most recent call last):\n  File \"c:\\Users\\geo_s\\Documents\\MICAI 2025\\MedMNIST\\.venv\\Lib\\site-packages\\keras_tuner\\src\\engine\\base_tuner.py\", line 274, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"c:\\Users\\geo_s\\Documents\\MICAI 2025\\MedMNIST\\.venv\\Lib\\site-packages\\keras_tuner\\src\\engine\\base_tuner.py\", line 239, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n  File \"c:\\Users\\geo_s\\Documents\\MICAI 2025\\MedMNIST\\.venv\\Lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 314, in run_trial\n    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n  File \"c:\\Users\\geo_s\\Documents\\MICAI 2025\\MedMNIST\\.venv\\Lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 232, in _build_and_fit_model\n    model = self._try_build(hp)\n  File \"c:\\Users\\geo_s\\Documents\\MICAI 2025\\MedMNIST\\.venv\\Lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 164, in _try_build\n    model = self._build_hypermodel(hp)\n  File \"c:\\Users\\geo_s\\Documents\\MICAI 2025\\MedMNIST\\.venv\\Lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 155, in _build_hypermodel\n    model = self.hypermodel.build(hp)\n  File \"C:\\Users\\geo_s\\AppData\\Local\\Temp\\ipykernel_27496\\4000496272.py\", line 46, in build_model\n    model.compile(optimizer=optimizer,\n                            ^^^^^^^^^\nUnboundLocalError: cannot access local variable 'optimizer' where it is not associated with a value\n"}